#!/bin/bash

org="https://github.com/axyl-os/"

declare -a pkgbuild_repos=(
pkgbuild
repo
core-repo
3party-repo
)

declare -a wm_repos=(
i3wm
bspwm
leftwm
spectrwm
xmonad
riverwm
dwm
qtile
)

declare -a base_repos=(
iso
calamares-config
os.github.io
dwmblocks
skeleton
scripts
lxdm-theme
grub-theme
dmenu
wallpapers
)

mkdir -p ./pkgbuild_repos ./wm_repos ./base_repos

(cd ./pkgbuild_repos; for i in ${pkgbuild_repos[@]}; do (git clone ${org}axyl-${i}); done)
(cd ./wm_repos; for i in ${wm_repos[@]}; do (git clone ${org}axyl-${i}); done)
(cd ./base_repos; for i in ${base_repos[@]}; do (git clone ${org}axyl-${i}); done)

if [[ ! -f "$HOME/.gitconfig" ]]; then
  git config --global user.email "matthewriel63@gmail.com"
  git config --global user.name "Kungger-git"
fi
