#!/bin/bash

declare -a repos=(
repo
skeleton
core-repo
pkgbuild
iso
bspwm
i3wm
leftwm
spectrwm
xmonad
calamares-config
qtile
os.github.io
scripts
repo-3party
dwm
dwmblocks
lxdm-theme
grub-theme
fonts
dmenu
)

for i in ${repos[@]}; do (git clone https://github.com/axyl-os/axyl-${i}); done
