#!/bin/bash

declare -a repos=(
repo
skeleton
core-repo
pkgbuild
iso
bspwm
i3wm
leftwm
spectrwm
xmonad
calamares-config
qtile
os.github.io
scripts
repo-3party
dwm
dwmblocks
lxdm-theme
grub-theme
fonts
dmenu
)

for i in ${repos[@]}; do (git clone https://github.com/axyl-os/axyl-${i}); done

if [[ -d "$PWD/axyl-pkgbuild" ]]; then
  cp ./upd-local.sh \
     ./upd-3party.sh \
     ./upd-core.sh ./axyl-pkgbuild/
fi

if [[ ! -f "$HOME/.gitconfig" ]]; then
  git config --global user.email "matthewriel63@gmail.com"
  git config --global user.name "Kungger-git"
fi
